name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0/8 * * *"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: youzipi/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 425ceea59323e97625729237758a00f7
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          
